name: Android CI

on:
  push:
    branches: [ flyme8 ]
  pull_request:
    branches: [ flyme8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        # Artifact name
       name: app
        # Destination path
        # path: app/build/outputs/apk/debug/xw-debug.apk
