name: Android CI

on:
  push:
    branches: [ flyme8 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android NDK
      # You may pin to the exact commit or the version.
      # uses: nttld/setup-ndk@7ecec22caa4fe94863d2dca55455b4d9ccded495
      uses: nttld/setup-ndk@v1.0.2
      with:
        # Exact version to use
        ndk-version: 22.0.6917172
    - name: Build with Gradle
      run: ./gradlew build
